# https://hub.docker.com/_/mysql
version: '3'

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: example
